apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app

  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 704741493320.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:12
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort